name: Build and Run Airflow Tests

on:
  push:
    branches:
      - main  # Change to match your default branch
  pull_request:
    branches:
      - main  # Change to match your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-airflow .

    - name: Run tests in Docker container
      run: |
        docker run --rm my-airflow pytest /opt/airflow/tests/
